/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view;

/**
 *
 * @author tramatnois
 */
public class Mainframe extends javax.swing.JFrame {

    /**
     * Creates new form Mainframe
     */
    public Mainframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_InspOperation = new javax.swing.JPanel();
        jPanel_Customer = new javax.swing.JPanel();
        jLabel_customer_name = new javax.swing.JLabel();
        jTF_customer_name = new javax.swing.JTextField();
        jButton_search_customer = new javax.swing.JButton();
        jLabel_storageRack = new javax.swing.JLabel();
        jTextField_storageRack = new javax.swing.JTextField();
        jButton_search_storageRack = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_main = new javax.swing.JMenu();
        jMenuItem_connect = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_InspOperation.setBorder(new javax.swing.border.MatteBorder(null));

        jPanel_Customer.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel_customer_name.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel_customer_name.setText("Auftraggeber:");

        jTF_customer_name.setEditable(false);
        jTF_customer_name.setText("customer_name");
        jTF_customer_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_customer_nameActionPerformed(evt);
            }
        });

        jButton_search_customer.setText(". . .");
        jButton_search_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_search_customerActionPerformed(evt);
            }
        });

        jLabel_storageRack.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel_storageRack.setText("Regalnummer:");

        jTextField_storageRack.setEditable(false);
        jTextField_storageRack.setText("storageRack ID");
        jTextField_storageRack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_storageRackActionPerformed(evt);
            }
        });

        jButton_search_storageRack.setText(". . .");
        jButton_search_storageRack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_search_storageRackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_CustomerLayout = new javax.swing.GroupLayout(jPanel_Customer);
        jPanel_Customer.setLayout(jPanel_CustomerLayout);
        jPanel_CustomerLayout.setHorizontalGroup(
            jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CustomerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_customer_name)
                    .addGroup(jPanel_CustomerLayout.createSequentialGroup()
                        .addComponent(jTF_customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_search_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addGroup(jPanel_CustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_storageRack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_storageRack, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_search_storageRack, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_CustomerLayout.setVerticalGroup(
            jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_customer_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_customer_name, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jButton_search_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_storageRack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_storageRack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_search_storageRack, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout jPanel_InspOperationLayout = new javax.swing.GroupLayout(jPanel_InspOperation);
        jPanel_InspOperation.setLayout(jPanel_InspOperationLayout);
        jPanel_InspOperationLayout.setHorizontalGroup(
            jPanel_InspOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InspOperationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Customer, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(415, Short.MAX_VALUE))
        );
        jPanel_InspOperationLayout.setVerticalGroup(
            jPanel_InspOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InspOperationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jMenu_main.setText("Menü");

        jMenuItem_connect.setText("...mit Datenbank verbinden");
        jMenuItem_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_connectActionPerformed(evt);
            }
        });
        jMenu_main.add(jMenuItem_connect);
        jMenu_main.add(jSeparator1);

        jMenuItem_exit.setText("Beenden");
        jMenu_main.add(jMenuItem_exit);

        jMenuBar1.add(jMenu_main);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_InspOperation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_InspOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_connectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_connectActionPerformed

    private void jTF_customer_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_customer_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_customer_nameActionPerformed

    private void jTextField_storageRackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_storageRackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_storageRackActionPerformed

    private void jButton_search_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_search_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_search_customerActionPerformed

    private void jButton_search_storageRackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_search_storageRackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_search_storageRackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_search_customer;
    private javax.swing.JButton jButton_search_storageRack;
    private javax.swing.JLabel jLabel_customer_name;
    private javax.swing.JLabel jLabel_storageRack;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_connect;
    private javax.swing.JMenuItem jMenuItem_exit;
    private javax.swing.JMenu jMenu_main;
    private javax.swing.JPanel jPanel_Customer;
    private javax.swing.JPanel jPanel_InspOperation;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTF_customer_name;
    private javax.swing.JTextField jTextField_storageRack;
    // End of variables declaration//GEN-END:variables
}
